### ISSUE TITLE
Compatibilty ContentBox3 layoutservice not found

### ISSUE THREAD

**Issue by danielosan** [contentbox-modules/slatwall-contentbox#8]
the layoutservice seem to be depreciated in CB3. Activation of the module fails with error
`var layoutService = wirebox.getInstance('layoutService@cb');`
line 36 in moduleconfig.cfc

**Comment by danielosan** [comment]
LayoutService was replaced by ThemeService

**Comment by lmajano** [comment]
Thanks, fixed

**Comment by danielosan** [comment]
another...

moduleConfig.cfc Line 40 from
 `var layout = ThemeService.getActiveLayout();` 
to
 `var layout = ThemeService.getActiveTheme();`

**Comment by danielosan** [comment]
SlatwallSetup.cfc needs a increase of the requesttime `<cfsetting requesttimeout=300/>`

**Comment by lmajano** [comment]
done

**Comment by danielosan** [comment]
Right know activation hangs on `/org/hibatchi/HibachiSmartList.cfc` with  a null pointer at Line 790 orm query. Thus far I could not figure out why. Standalone installs fine.

**Comment by danielosan** [comment]
because /slatwall/config/configApplication.cfm did not update with application-name, database and additional mappings. Did it manually, but more issues now regarding the binder slatwallSyncService not found in interceptor-slatwall

**Comment by lmajano** [comment]
Hmm, I think now you might need to contact @gregmoser on this.

**Comment by gregmoser** [comment]
@danielosan can you post the entire stack trace error on the Slatwall google group.  It may be a bug in Slatwall in which case we can open an issue over there.  Our google group can be found at: http://www.slatwallcommerce.com/community
